---
  environment: production
  user: tangtao
  group: tangtao
  port: 7000
  pid: log/thin.pid
  rackup: config.ru
  log: log/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: true
